import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Link from "next/link";
import Navbar from "../../components/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Layout 2",
    description: "Generated by jesus eng",
};

export default function Layout({ children }: Readonly<{ children: React.ReactNode }>) {
    return (
        <html lang="en">
            <body className={inter.className}>
                <header className="bg-blue-900">
                    <Navbar />
                </header>
                {children}
            </body>
        </html>
    );
}